### PR TITLE
Update ch_SIMP.json

### PR DESCRIPTION
**Pull request by soyoker**

### CODE REVIEW

**Comment by opdev1004** [comment]
Thank you for your contribution.
The translation will be updated in next version.
Do you own JS Page?

**Comment by soyoker** [comment]
> Thank you for your contribution.
> The translation will be updated in next version.
> Do you own JS Page?

Not yeat,but with deeply interested

**Comment by opdev1004** [comment]
Is this your email address? soyoker@outlook.com

**Comment by soyoker** [comment]
> Is this your email address? [soyoker@outlook.com](mailto:soyoker@outlook.com)

Yeah,it is.

**Comment by opdev1004** [comment]
Check your email for the free JS Page product key.
It is up to you how you use it.
Thank you for your contribution. 🙂

**Comment by soyoker** [comment]
Thank you very much.

**Pull request merged**
